### ISSUE TITLE
hjson

### ISSUE THREAD

**Issue by laktak** [hjson/mujupj-hjson#1]
Hi!

We are in the process of creating an organization for http://hjson.org. It would be great if we could name it hjson (the name you are currently using).

Would you mind and would it be possible for you to change your username? 

Please let us know. Thanks.

**Comment by hjson** [comment]
i dont know English.
Please tell me in Hangul
 
 
(주)손형주

H . P : 010-4154-0062

FAX  : 

MAIL : pviivq@naver.com
 
-----Original Message-----
